### ISSUE TITLE
Assign/Unassign `Contributor` Discord Role based on `Circle Membership`

### ISSUE THREAD

**Issue by reeserj** [coordinape/discord-bot#24]
[Notion](https://www.notion.so/coordinape/CO-Kong-Discord-Bot-411f0a9d02eb4983b2611a5b5cec3166#fbeb856ac34d4b03ab8f5cf16395a96e)

# Description
- As a `Circle Admin` I want to add a `user` to a Coordinape Circle so they can have the 'Discord Role' associated with that circle
- As a `Circle Admin` I want to remove a `user` from a Coordinape Circle so the 'Discord Role' associated with that circle will be removed from their account in Discord. 

By default the role name in Discord should be "`circle name ` + Coordinape" but will be referred to as `Contributor` in these specs

## Add user 

1. When `Contributor` **has not linked** Discord to Coordinape
    1. Send `Success Message` in the circle's assigned Discord Channel: 
        >"[Username] - [0x+last 4 of address] has been added to the [circle name] circle via [method of addition] _magic link, csv input, or manually._
        >
        >[admin role] please ask the user to use the /coordinape command and click the `Link` button to get the most out of the discord bot! 
         [#26](https://github.com/coordinape/discord-bot/issues/26)
2. When `Contributor` **has linked** Discord to Coordinape
    1. Send `Success Message` in the circle's assigned Discord Channel: 
        >"[Discord Username] has been added to the [circle name] circle via [method of addition] _magic link, csv input, or manually._ _**-- therefore role X was added to them**_ reese
 
## Remove user
1. When `Contributor` **has not linked** Discord to Coordinape
    1. Send `Success Message` in the circle's assigned Discord Channel: 
        >"[Username] - [0x+last 4 of address] has been removed to the [circle name] circle via [method of removal] _admin or manually._ **-- therefore role X was removed from them**_ reese
  
2. When `Contributor` **has linked** Discord to Coordinape
    1. Send `Success Message` in the circle's assigned Discord Channel: 
        >"[Discord Username] has been removed to the [circle name] circle via [method of removal] _admin or manually._

# Context
In order to manage Discord Roles from the app, the bot needs the ability to assign/unassign `contributor` roles to/from a discord account when a contributor is added/removed from a circle.

# Acceptance Criteria
When a contributor is added or removed from a circle their role is updated in discord. 
- Only the expected role will be removed/added
- All messages appear as expected.

# Open Questions
NA

- [ ] Do we already have these: magic link, csv input, or manually.

**Comment by karelianpie** [comment]
Done
