### ISSUE TITLE
Create `Epoch Update` messages

### ISSUE THREAD

**Issue by reeserj** [coordinape/discord-bot#28]
## Description

* As a `Circle Member`, I want to `be updated on Circle Events` so that `I can know what I should be doing`

- All times should use unix time code when being displayed ([Hammertime](https://hammertime.cyou))

1. Epoch Event triggers message to be sent in Discord

Button links until we can develop the automatic replies:

- `Link` (What ever URL they need to link their account to the discord bot)
- `Contribute` (https://app.coordinape.com/circles/`[Circle number]`/contributions
- `Epoch Statement`(https://app.coordinape.com/circles/`[circle number ]`/give)
- `Opt-in` `(https://app.coordinape.com/circles/`[circle number ]`/give)
- `Coordinape.com` (Coordinape.com)
- `Pulse Survey` (Comment this out for now )
- `Personal Summary` (Comment this out for now)
- `Vouch` (https://app.coordinape.com/circles/`[Circle Number]`/members)

### Events

1. **Epoch Start**
    >Heads up **[role]**! **[epoch name]** for **[circle]** has just started! 
    > 
    > It will run from **[start date<t:1668223320:f>]** to **[end date<t:1668223320:f>]**   **<t:1665417300:R>** ! 
    > 
    > Don’t forget to opt in and let your Circlemates know what you did this this cycle in your epoch statement and contributions! 
    > 
    > If you want to opt-in or update your statement you can do that by clicking the buttons below.
    > 
    > **Get Giving**
    > 
    >`Link` `Contribute` `Epoch Statement` `Opt-in` `Coordinape.com` 

2. **Epoch End**
    > **[role]** You've done it! **[epoch name]** for **[circle]** ended <t:1665417300:R>! 
    > 
    > I’m sure you crushed it. Your Circle gave [SUM give] across [count users]. 
    > 
    >To see your results for the epoch click the Personal Summary button below, or view it in the app. [circle history link]
    > 
    > We’d love to know how you felt about this epoch, if you react to this message we’ll use that data to make Coordinape better!
    > 
    > If you have 3 minutes you could also fill out the pulse survey below this data will help your team and Coordinape improve.
    >
    > **It's better to GIVE than receive**
    > 
    >`Pulse Survey` `Link` `Contribute` `Personal Summary` `Coordinape.com` 
3. **Nomination**
    > **[role]** [Nominee] was nominated by [Nominator] for [Nomination reason] <Nomination time t:1665417300:R>! 
    > 
    > They need [number of vouches] vouches to join the circle.
    > 
    > `Vouch` `Link` `Coordinape.com` 
4. **Vouch**
    > **[role]** [Nominee] was Vouched for by [Voucher] for [Nomination reason] <Vouch time t:1665417300:R>! 
    > 
    > They need [number of vouches] vouches to join the circle.
    > 
    > `Vouch` `Link` `Coordinape.com` 
5. **Vouch Successful**
    > **[role]** [Nominee] was successfully Vouched into the Circle [Voucher1, Voucher N] for [Nomination reason] <final vouch time t:1665417300:R>! 
    > 
    > Don't forget to welcome them to the circle with a note! 
    > 
    > `Note` `[Nominee Profile]` `Link` `Coordinape.com` 
5. **Vouch Unsuccessful**
    > **[role]** [Nominee] did not receive enough vouches to join the circle their Nomination has expired. They can be renominated now. 
    > 
    > `Nominate` `Link` `Coordinape.com` 
6. **User Added to Circle**
    > **[role]** [New User], [Username] - [0x+last 4 of address] has been added to the [circle name] circle via [method of addition] _ successful Vouch, magic link, csv input, or manually_
    >
    > Don't forget to welcome them to the Circle with a note in the next Epoch! 
    >
    > `Note` `Link` `Coordinape.com` 
7. **User Leaves Circle**
    > [Username] - [0x+last 4 of address] has left the [circle name] circle via [method of removal] _ manual, admin removal_
    >
    > [Give allocated] was refunded to [Username 1]... [Give allocated] was refunded to [Username n]
    >
    > `Link` `Coordinape.com` 
8. **User Opts Out**
    > [Username] - [0x+last 4 of address] has opted out of the current Epoch for [circle name] circle.
    >
    > [Give allocated] was refunded to [Username 1]... [Give allocated] was refunded to [Username n]
    >
    > `Link` `Coordinape.com` 

## ⚠ (WIP) Technical Details

* Create the commands;
* Check if the user has linked discord;
* Mutation to add/remove user to/from circle;
* Display response

## Context

The Coordinape App currently has events that trigger a webhook, we want to listen to those events and send messages when prompted.
[Notion Link](https://www.notion.so/coordinape/CO-Kong-Discord-Bot-411f0a9d02eb4983b2611a5b5cec3166#e32d254fb4024b16b9b59eacbe8d8342)

## Acceptance criteria

- All Commands work as expected and open questions answered.
- All Commands happen within ~2 minutes of the event
- Gracefully handle instances where we don't have linked users.

## Open Questions

- [x] Would be cool if we could use progress bars for vouching progress ▰▰▰▰▰▰▰▰▱▱
- [x] Can the link to the user profile be dynamically updated for the vouched users?
- [ ] Can the New User prompt be smart enough to include the vouch data, or should we have two separate messages?
- [x] Anywhere where we use the [username], [nominee], [Voucher], etc we should use their discord handle if we have it, but if we don't just use their name and last 4 of address [Reese - 4002]

**Comment by reeserj** [comment]
Is the url where people link their discord to Coordinape not a static link?
@karelianpie 

I thought it would just be a page similar to their profile page that would let them link their discord to the app

**Comment by karelianpie** [comment]
> Is the url where people link their discord to Coordinape not a static link? @karelianpie
> 
> I thought it would just be a page similar to their profile page that would let them link their discord to the app

It is a static link, but the linking happens behind the scenes and they get a toast as confirmation -- the idea of a page was not necessary as they can just get linked without any further action so the designer dropped the page

**Comment by karelianpie** [comment]
Done
