### ISSUE TITLE
Display Profile name when a new user is added if they have one

### ISSUE THREAD

**Issue by reeserj** [coordinape/discord-bot#86]
![Image](https://user-images.githubusercontent.com/82838264/221197099-6419975e-3e57-443b-84f4-14f095be3194.png)

Currently when an user is added who's not in the discord and linked their account it shows the last 4 of their address, I think it should show their profile name in () if we have it. 

Like this @Jewelery Member, Ox...0728 `Profile Name` has been added to the circle

**Comment by karelianpie** [comment]
Just to clarify here, how exactly should the message be?

> Ox...0728 Reese has been...

or 

> Ox...0728 (Reese) has been...

or

> Reese Ox...0728 has been...

**Comment by karelianpie** [comment]
> @reeserj just to clarify here, how exactly should the message be?
> 
> > Ox...0728 Reese has been...
> 
> or
> 
> > Ox...0728 (Reese) has been...
> 
> or
> 
> > Reese Ox...0728 has been...
> 
> and it's the username or profile name?

Went with

> Ox...0728 Reese has been...
