### ISSUE TITLE
Epoch Alerts not getting triggered

### ISSUE THREAD

**Issue by reeserj** [coordinape/discord-bot#89]
The alerts for Epoch start and end are not getting triggered

**Comment by karelianpie** [comment]
Condition for epoch end trigger
```typescript
notifyEndEpochs: {
  epochs: [
    {
      where: {
        _and: [
          { end_date: { _gt: 'now()' } },
          { end_date: { _lte: inTwentyFourHours } },
        ],
        start_date: { _lt: 'now()' },
        notified_before_end: { _is_null: true },
      },
    },
  ],
},
```

Start date less than now, end date more than now but less than or equal to 24 from now

@reeserj fyi we don't get a notification when the epoch actually ends, but 24h in advance
