### ISSUE TITLE
Cron Job sending an epoch start message every 10 minutes

### ISSUE THREAD

**Issue by reeserj** [coordinape/discord-bot#98]
The bot is getting messages from the chron job every 10 minutes

**Comment by karelianpie** [comment]
The cron is in `api/hasura/cron/epochs.ts` and the function being called is `notifyEpochStart`, which in turn calls `sendSocialMessage` in

```typescript
    if (
      isFeatureEnabled('discord') &&
      channelId &&
      roleId &&
      alerts?.['epoch-start']
    ) {
      await sendSocialMessage({
        message,
        circleId: circle.id,
        channels: {
          isDiscordBot: true,
          discordBot: {
            type: 'start' as const,
            channelId,
            roleId,
            epochName: `Epoch ${epochNumber}`,
            circleId: circle.id,
            circleName: `${circle.organization?.name}/${circle.name}`,
            startTime: start_date,
            endTime: end_date,
          },
        },
        sanitize: false,
      });
      updateEpochStartNotification(epoch.id);
    }
```

**Comment by karelianpie** [comment]
@CryptoGraffe this issue is in https://github.com/coordinape/coordinape, the app is just calling the bot endpoint and the bot is posting the message. The problem is that the coordinape app is always triggering the epoch start event, even when it was already sent in the previous run

**Comment by karelianpie** [comment]
@CryptoGraffe @reeserj had a look at this, https://github.com/coordinape/coordinape/pull/1997
